#------------------------
# Vlad Borovkov
#------------------------
name: Make-lint

on: [push]

jobs:

  make_lint:
    
    runs-on: ubuntu-latest

    
    steps:

      - name: Run make lint
        run: make lint
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
